In [15]:
import numpy as np
a=np.array([1,2,3])
print(a)
# 2d array
b=np.array([[1,2,3],[2,34,4]])
print(b)
print()
c=np.array([[1,2,3],[2,34,4],[4,5,6]])
print(c)
print(type(c))

[1 2 3]
[[ 1  2  3]
 [ 2 34  4]]

[[ 1  2  3]
 [ 2 34  4]
 [ 4  5  6]]
<class 'numpy.ndarray'>


In [18]:
# Initialize an array of ‘x’ X ‘y’ dimension with 0
np.zeros([5,3], dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# Arranging the numbers between x and y with an interval of z 
np.arange(10,25,5)

array([10, 15, 20])

In [43]:
# Arranging ‘z’ numbers between x and y
print(np.linspace(5,7,6, dtype=int))
print(np.linspace(5,7,6, dtype=float))
print(np.linspace(5,7,6)) # default is float

print(np.arange(5,7,6))

[5 5 5 6 6 7]
[5.  5.4 5.8 6.2 6.6 7. ]
[5.  5.4 5.8 6.2 6.6 7. ]
[5]


In [57]:
# Filling SAME number in a array of dimension x X y 
np.full((3,2),3, order='F') # or np.full([3,2],3)

array([[3, 3],
       [3, 3],
       [3, 3]])

In [58]:
# Filling RANDOM numbers in a array of dimension x X y 
np.random.randint((2,2))

array([1, 1])

In [85]:
# ndarray.shape 
c=np.array([[1,2,3],[2,34,4]])
print(c.shape,'\n')
c.shape=(3,2)
print(c)

(2, 3) 

[[ 1  2]
 [ 3  2]
 [34  4]]


In [86]:
# ndarray.size
# “Returns the count of number of elements in an array.”
c.size

6

In [100]:
# ndarray.ndim
# “Returns the dimension of the array.
a=np.arange(24)
print(a.ndim)
b=a.reshape(2,4,3)
print(b.ndim)

1
3


In [119]:
# Addition using Numpy similar operations to subtract/multiply/division
print(c.sum())

print(np.sum([3,3]))

a,b=3,5
print(np.sum([a,b]))

c= np.sum(([[0,1],[0,5]]), axis=0)  #add vertically
print(c)

d= np.sum(([[0,1],[0,5]]), axis=1) # add horizontally
print(d)


6
6
8
[0 6]
[1 5]


In [125]:
# other calculation
print(np.exp(3))
print(np.sqrt(3))
print(np.sin(3))
print(np.cos(3))
print(np.log(3))

20.085536923187668
1.7320508075688772
0.1411200080598672
-0.9899924966004454
1.0986122886681098


In [135]:
# Element-wise Comparison 
a=[1,2,3]
b=[3,2,1]
c=[1,2,3]
print(np.equal(a,b))
print(np.equal((a,b),(a,c)))

# Array-wise Comparison 
print(np.array_equal(a,b))


[False  True False]
[[ True  True  True]
 [False  True False]]
False


In [140]:
# Aggregate Functions 
a=[1,2,3]
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.corrcoef(a))
print(np.std(a))


6
1
3
2.0
2.0
1.0
0.816496580927726


In [146]:
# Concept of Broadcasting 
a=np.array([[1,2,3],[2,4,1]])
b=np.array([[1,2,3], [3,2,1]])
print('First array:\n',a,'\n')
print('Second array:\n',b,'\n')
print('First array + Second array \n',a+b)
print('First array - Second array \n',a-b)
print('First array * Second array \n',a*b)
print('First array / Second array \n',a/b)

First array:
 [[1 2 3]
 [2 4 1]] 

Second array:
 [[1 2 3]
 [3 2 1]] 

First array + Second array 
 [[2 4 6]
 [5 6 2]]
First array - Second array 
 [[ 0  0  0]
 [-1  2  0]]
First array * Second array 
 [[1 4 9]
 [6 8 1]]
First array / Second array 
 [[1.         1.         1.        ]
 [0.66666667 2.         1.        ]]


In [167]:
# Indexing and slicing in Python 
a=np.array([[1,2,3],[2,4,1]])
print(a[0])
print('only rows',a[0:])
print('only columns',a[:,1])
print('\n',a[0:,1:])


[1 2 3]
only rows [[1 2 3]
 [2 4 1]]
only columns [2 4]

 [[2 3]
 [4 1]]


In [186]:
# Concatenating two arrays together 
a=np.array([1,2,3])
b=np.array([3,2,1])
print(np.concatenate((a,b),axis=0))

# Stack arrays row-wise(vertically) 
print('\n',np.vstack((a,b)))

# Stack arrays column-wise(horizontally) 
print('\n',np.hstack((a,b)))

# Combining column wise stacked array 
print('\n',np.column_stack((a,b)))

[1 2 3 3 2 1]

 [[1 2 3]
 [3 2 1]]

 [1 2 3 3 2 1]

 [[1 3]
 [2 2]
 [3 1]]


In [195]:
# Splitting Arrays 
x= np.arange(16).reshape(4,4)
print(x, '\n\n')
print(np.hsplit(x,2),'\n\n')
print(np.hsplit(x, np.array([3,6])))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])] 


[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]]), array([], shape=(4, 0), dtype=int32)]
