In [14]:
# vector
import numpy as np
v=np.array([5,-2,4])
v

array([ 5, -2,  4])

# matrices


In [9]:
m=np.array([[5,-2,6],[4,3,-5]])
m

array([[ 5, -2,  6],
       [ 4,  3, -5]])

# type

In [10]:

type(v)
type(m)


numpy.ndarray

# Data shapes


In [11]:
m.shape

(2, 3)

In [12]:
v.shape

(3,)

# Reshape

In [18]:
v.reshape(1,3)


array([[ 5, -2,  4]])

In [17]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

# Tensor 

In [19]:
m1=np.array([[5,-2,4],[5,42,4]])
m1

array([[ 5, -2,  4],
       [ 5, 42,  4]])

In [20]:
m2=np.array([[5,-2,0],[5,4,-5]])
m2

array([[ 5, -2,  0],
       [ 5,  4, -5]])

In [21]:
t=np.array([m1,m2])
t

array([[[ 5, -2,  4],
        [ 5, 42,  4]],

       [[ 5, -2,  0],
        [ 5,  4, -5]]])

In [22]:
t.shape

(2, 2, 3)

# addition

In [23]:
m1+m2

array([[10, -4,  4],
       [10, 46, -1]])

# exception 

In [26]:
m3=m1+3
m3

array([[ 8,  1,  7],
       [ 8, 45,  7]])

# transposing matrix

In [27]:
m3.T

array([[ 8,  8],
       [ 1, 45],
       [ 7,  7]])

# Dot product



In [28]:
a=np.array([5,4,2])
b=np.array([4,-4,5])
np.dot(a,b)

14

In [29]:
# scalar * scalar
np.dot(5,6)


30

In [31]:
# scalar * vector
6*a

array([30, 24, 12])

# dot prd. of matrices

In [34]:
a=np.array([[5,6],[3,3],[9,9]])
b=np.array([[2,3],[2,1]])
np.dot(a,b)


array([[22, 21],
       [12, 12],
       [36, 36]])