## Problem Statement:
You work in XYZ Corporation as a Data Analyst. Your corporation has told you to use the numpy
package and do some tasks related to that:
Tasks to be performed:


In [10]:
# 1. Create a 3x3 matrix array with values ranging from 2 to 10.
import numpy as np
a=np.arange(2,10)
print(a)

[2 3 4 5 6 7 8 9]


2. Create a numpy array having user input values and convert the integer type to the float type
of the elements of the array. For instance:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]


In [32]:
x=int(input('Enter the (1+last) value of array: '))
a=np.arange(1,x)
print(a)
b=a.astype(float)
print(b)


Enter the (1+last) value of array: 5
[1 2 3 4]
[1. 2. 3. 4.]


3. Write a Numpy program to append values to the end of an array. For instance:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]




In [41]:
o=np.array([10,20,30])
p=np.append(o,[40,50,60,70,80,90])
print(p)

[10 20 30 40 50 60 70 80 90]


4. Create two numpy arrays and add the elements of both the arrays and store the result in
sumArray

In [43]:
a=np.array([1,2,3])
b=np.array([4,5,6])
sumarray=np.sum(a+b)
print(sumarray)

21


5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform
the following tasks:
a. Extract the 1st row from the array.
b. Extract the last element from the array.

In [49]:
array1=np.arange(10,90,10)
print(array1)

[10 20 30 40 50 60 70 80]


In [63]:
# a. Extract the 1st row from the array. 
print(array1[0:])

# b. Extract the last element from the array.
print(array1[-1:])

[10 20 30 40 50 60 70 80]
[80]
