## Problem Statement:
You work in XYZ Company as a Python. The company officials want you to build a python program.
Tasks to be performed:

In [19]:
# 1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a Numpy array of the given 
# dimension filled with the given value e.g.: solve((3, 3), 5) will return 
'''[
 [5, 5, 5],
 [5, 5, 5],
 [5, 5, 5]
]
'''
import numpy as np
a=np.full([3,3],5)
print(a)                # observe the difference between print(a) and a only
a

[[5 5 5]
 [5 5 5]
 [5 5 5]]


array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [20]:
# 2. Create a method that takes n Numpy arrays of same dimensions sums them and return the answer
a.sum()

45

In [31]:
# 1. and 2. problems with input from the user
p=int(input('Please enter the value of number in array: '))
q=int(input('Please enter the number of rows in array: '))
r=int(input('Please enter the number of columns in array: '))
a=np.full([q,r],p)
print('The array for %d number with %d rows and %d columns is:\n'%(p,q,r),a)
print('The sum of the array is: ', a.sum())

Please enter the value of number in array: 6
Please enter the number of rows in array: 5
Please enter the number of columns in array: 4
The array for 6 number with 5 rows and 4 columns is:
 [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
The sum of the array is:  120


 3. Given a 2 D Array of N X M Dimension, 
Write a function that accepts this array as well as two numbers N and M. The method should return the top-left N X M sub matrix e.g:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
top_left_sub_matrix (matrix, 2, 2) -> should return:
 [
 [1, 2]
 [4, 5]
 ]

In [36]:
# Write a function that accepts this array as well as two numbers N and M. e.g: [ [1, 2, 3], [4, 5, 6], [7, 8, 9], ]
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
# top_left_sub_matrix (matrix, 2, 2) -> should return:
b=a[:2,:2]
print(b)

[[1 2]
 [4 5]]


4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
 [
 [5, 6]
 [8, 9]
 ]

In [35]:
# sub_matrix(matrix, 1, 1) -> should return :[ [5, 6] [8, 9] ]
c=a[1:,1:]
print(c)

[[5 6]
 [8 9]]


5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method
should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's
standard deviation as values:
 [1, 1, 1]
solution(arr) -> should return :
 {'mean': 1.0, 'std_dev': 0.0}

In [74]:
d=np.array([1,1,1])
e=d.mean()
f=d.std()
print('mean is :',e)
print('standard deviation is :', f)
print('In dictionary format: ')
a={'mean':e, 'std_dev':f}
print(a)

mean is : 1.0
standard deviation is : 0.0
In dictionary format: 
{'mean': 1.0, 'std_dev': 0.0}
