# Numpy Operations



In [1]:
import numpy as np

In [3]:
#  Create np array of zeroes of size (2, 3) run the following code.
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# Flatten 2D np Array to 1d np array
ar=np.array([[1,2,3],[4,5,6]])
ar.ravel()

array([1, 2, 3, 4, 5, 6])

In [10]:
#  Convert 1D np Array to 2d np array from a python list:
arr=np.reshape(ar,(3,2))               
arr

# or ar.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
# Create np array and sort sort
ar=np.array([1,9,5,6,3,4])
ar.sort()
print(ar)

[1 3 4 5 6 9]


In [26]:
# Slice an np array to create another array without the first two elements of the original array
a=np.array([1,2,3,4,5,6])
b=a[2:]
b

array([3, 4, 5, 6])